# Generated by Django 5.1 on 2024-09-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='doctor',
            name='contact_number',
            field=models.CharField(default='1234567890', max_length=15),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default='@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
